database-type: mysql
mysql:
    host: localhost
    port: 3306
    database: database
    username: username
    password: password
    prefix: econ_
    auto-create: true
currency:
    prefix: $
    singular: Dollar
    plural: Dollars
economies:
    main:
        starting-balance: 0;
        worlds:
            - world
            - world_nether
            - world_the_end