name: BattleConomy
load: startup
main: net.battlenexus.bukkit.economy.BattleConomy
version: 1.0.0-beta1
author: Lavoaster
softdepend: [Vault]
loadbefore: [Essentials]
commands:
   bc:
      aliases:
        - money
        - m
      description: BattleEconomy Command.
      usage: /<command> [option] [arguments]
   bc balance:
      aliases:
        - balance
      description: View your balance.
      usage: /<command> [economykey] [player]